#!/bin/sh
set -e

# Build debug
if test ! -f output/config  || test ! `cat output/config` = DEBUG; then
	echo "Cleaning output"
	make clean > /dev/null
fi
echo "Building in debug mode"
make MODE=DEBUG > /dev/null

# Upload build
echo "Uploading deployment"
rsync -ru --delete --exclude ".git" --exclude ".vagrant" --exclude "node_modules" ./ $1:~/debug

# Run debug deployment
echo "Running deployment"
ssh -q $1 > /dev/null <<- END
cd ~/debug
npm install --production
export PORT=8080
pm2 delete ruleswaps-debug
pm2 start output/server.js --name ruleswaps-debug
END