version: "3.7"
services:
  app:
    build: .
    restart: always
  proxy:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - /etc/letsencrypt:/etc/letsencrypt
      - /var/certbot/www:/var/www/certbot
    ports:
      - 80:80
      - 443:443